### ISSUE TITLE
Killed error

### ISSUE THREAD

**Issue by NurgulKaryagis** [SharifAmit/RVGAN#14]
Hi,

I got this error. I tried to drop batch size, it didn't work. 

![Screenshot from 2022-03-08 09-38-25](https://user-images.githubusercontent.com/35428800/157181960-ab2e81b2-83f4-4874-82d4-133a3d2e5618.png)

System features as below:
![Screenshot from 2022-03-08 09-40-00](https://user-images.githubusercontent.com/35428800/157182121-6af57cff-7916-4872-b80e-366629eafa8d.png)

Thank you

**Comment by SharifAmit** [comment]
Hi,

We used TF-gpu with 16GB of GPU memory, to train our model in google colab. Also, there were around 20GB of RAM memory which was available during training. 

Given your system only has 15.3 GB of RAM in total for running the model, I am assuming you are facing out of memory issue. Hence the linux process was killed without throwing any issue.

You can check the following issue in Tensorflow regarding your particular problem.

Link https://github.com/tensorflow/models/issues/3497

Closing this issue, as it is not related to our particular model.
