### ISSUE TITLE
local_plot predictions always blank

### ISSUE THREAD

**Issue by Medicmind** [SharifAmit/RVGAN#15]
I am trying to train the DRIVE data with RVGAN-tf-2.6. An issue I'm finding is the predictions in local_plot are always blank even after 53 epochs of training which took over 20 hours:

![local_plot_000053](https://user-images.githubusercontent.com/41133853/158464002-2929d435-02f2-4c03-be9b-cb65ced173df.png)
local_plot_000053.png

The global_plot though is visible
![global_plot_000053](https://user-images.githubusercontent.com/41133853/158464012-b2fb5f47-5d4f-4bac-982d-219320186a6d.png)
global_plot_000053.png

I am trying to reproduce eval.py IOU values but the predictions are always blank and looks like it is because predictions from g_local_model are always blank though not from g_global_model

**Comment by SharifAmit** [comment]
Hi,

We have not tested or experimented on tf-2.6 gpu version for our model. Please use the original tf-2.0 gpu implementation to replicate our experiment.

This version was created in response to this [issue](https://github.com/SharifAmit/RVGAN/issues/8)

All I can suggest is to train for longer for g_local_model to get good output. As It was mentioned in the paper to train for 100 epochs in three stages to get good output. So You need to resume training by loading weights for both g_local and g_global after 100th epoch. And in total you need to do it for 300 epochs (3 stages).

Hope this answers your questions.

**Comment by Medicmind** [comment]
Thanks. Yes, I'm getting much better results with tf-2.0gpu.  Seeing segmentation in both local and global.
