### ISSUE TITLE
How to determine the best model

### ISSUE THREAD

**Issue by icyclv** [SharifAmit/RVGAN#16]
Hi!Thank you for your work！
I'm a little confused that you said，we should looped over all 100 saved weights to find the best performing coarse and fine generator pairs and train again.Which data do we use to determine the best model？

**Comment by SharifAmit** [comment]
Hi 

You can check with holdout test set and using the eval.py file, We only evaluate after the third stage ( after training for 100 epochs 3 times). 

https://github.com/SharifAmit/RVGAN/blob/master/eval.py

Hope this answers your question.

**Comment by icyclv** [comment]
Thank you for your reply.
I have a question that will the results differ between the two versions(tf2.0 and tf2.6)?Because I have trained the model on tf26 branch,but the f1 score is around 0.75.

**Comment by SharifAmit** [comment]
Hi,

I highly recommend using tf 2.0. As the original model, loss implementation and training was carried out in that version. tf 2.6 was implemented solely for the following issue (Link:  https://github.com/SharifAmit/RVGAN/issues/8) and we have not formally verified the training or evaluation on that.


Hope this helps.

Thanks

**Comment by icyclv** [comment]
Thanks for your work!
