### ISSUE TITLE
need help!

### ISSUE THREAD

**Issue by victory3398** [SharifAmit/RVGAN#17]
Hello! can you send me your generated dataset npz file?  I can't generate is using your code

**Comment by SharifAmit** [comment]
Hi,

Can you share what error are you facing to generate the dataset ? If we can fix this problem, others might find it helpful.

Thanks!

**Comment by SharifAmit** [comment]
Hi, 

This seems like a duplicate issue to [issue 18](https://github.com/SharifAmit/RVGAN/issues/18).

So, I'm closing this one.

Thanks!
