### ISSUE TITLE
Hi~

### ISSUE THREAD

**Issue by victory3398** [SharifAmit/RVGAN#19]
I try to do your work,but meet a bug.
![03000ae4a968fc3b9ded2c3f3859ed4](https://user-images.githubusercontent.com/58261912/200152922-b21a8151-2f83-4a97-ab68-8260806e536b.png)
![22a7fb94e3a7319d711d6881d25c0e9](https://user-images.githubusercontent.com/58261912/200152927-ea9c4021-849f-431d-aa9b-4bc9723af500.png)
![2e5832eb14769d749ec282c29f0c718](https://user-images.githubusercontent.com/58261912/200152932-7b4eb866-9c7e-47a4-aa7a-6dbd69cffb9f.png)
My tensorflow is 2.7.4 and keras is 2.7.0.  I don't know what whould I do.

**Comment by SharifAmit** [comment]
Hi,

Our official implementation is in TF 2.0. please check the following branch https://github.com/SharifAmit/RVGAN/tree/tf-2.6 which might work for your case.

However we have not officially trained or tested this version.

I'm closing this issue.
