### ISSUE TITLE
How should we train the model using tf 2.6.0?

### ISSUE THREAD

**Issue by xiaogangzhu** [SharifAmit/RVGAN#8]
Hi, I tried training the model on tf 2.6.0 and some problems happens. How should i fix this? 
![2021-10-20 16-10-57 的屏幕截图](https://user-images.githubusercontent.com/65101307/138054102-270533a6-d772-4e92-ac1a-e0abf13c634e.png)

**Comment by SharifAmit** [comment]
Currently we are not planning to create a branch that supports TF 2.6.0. 

However, you can check one of our recent works which utilizes TF 2.6.0, where we used similar Coarse and Fine generators, and  Discriminator with a embedding feature-matching loss. The overall training is quite similar, and should be reproducible for RVGAN.

[Link](https://github.com/SharifAmit/VTGAN)

Hope this helps !

**Comment by SharifAmit** [comment]
I have created a new branch for tf 2.6.0

Link: https://github.com/SharifAmit/RVGAN/tree/tf-2.6

Please open a new issue if have any error.

Thanks!

**Comment by xiaogangzhu** [comment]
Thank you!
